export const homeObjOne = {
      id: 'about',
      lightBg: false,
      lightText: true,
      lightTextDesc: true,
      topLine: 'Premium Bank',
      headline: 'Unlimited Transactions with zero fees',
      description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
      direction:'row',
      buttonLabel: 'Get started',
      imgStart: false,
      img: require('../images/off-road.svg'),
      alt: 'Car',
      dark: true,
      primary: true,
      darkText: false,
      redirectLink: '/',
}

export const homeObjTwo = {
      id: 'discover',
      lightBg: true,
      lightText: false,
      lightTextDesc: false,
      topLine: 'Unlimited Access',
      headline: 'Unlimited Transactions with zero fees',
      description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
      direction:'row-reverse',
      buttonLabel: 'Learn More',
      imgStart: true,
      img: require('../images/savings.svg'),
      alt: 'Piggy bank',
      dark: false,
      primary: false,
      darkText: true,
      redirectLink: '/',
}

export const homeObjThree = {
      id: 'signup',
      lightBg: false,
      lightText: true,
      lightTextDesc: true,
      topLine: 'Free Account',
      headline: 'Unlimited Transactions with zero fees',
      description:"Sign up means to register; to create an account. In computing, sign in and log in are synonyms. Both mean to open a session with an account that is already created.",
      direction:'row',
      buttonLabel: 'Create Account',
      imgStart: false,
      img: require('../images/sign-in.svg'),
      alt: 'Paper',
      dark: true,
      primary: true,
      darkText: false,
      redirectLink: '/signup',
}